# You can omit the nodePort field, in which case the port number given by the port field will be used.
# The manifest above specifies that Node port 32000 will direct traffic to port 80 at your app: nginx Pods.

# kubectl apply -f nodeport.yaml

apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      nodePort: 32000
